import { isRelayOk, relayBytes } from "@/lib/client/cors-fetch";
import { slugify } from "@/lib/utils";

/**
 * One download path for everything: images, tracks, PDFs, QR codes, reports.
 * A direct fetch keeps the browser's own "Save" flow; when the source refuses
 * cross-origin reads, the relay chain fetches the bytes instead; only when no
 * route exists does the file open in a tab so the analyst still has it.
 */

export type DownloadMode = "blob" | "relay" | "opened" | "failed";

function extensionFromMime(mime: string): string | undefined {
  const map: Record<string, string> = {
    "image/jpeg": ".jpg",
    "image/png": ".png",
    "image/webp": ".webp",
    "image/svg+xml": ".svg",
    "image/gif": ".gif",
    "application/pdf": ".pdf",
    "audio/mpeg": ".mp3",
    "audio/mp4": ".m4a",
    "audio/aac": ".aac",
    "audio/ogg": ".ogg",
    "audio/wav": ".wav",
    "video/mp4": ".mp4",
    "video/webm": ".webm",
    "text/plain": ".txt",
  };
  return map[mime.split(";")[0].trim()];
}

function saveBlob(blob: Blob, filename: string): void {
  const objectUrl = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = objectUrl;
  anchor.download = filename;
  anchor.rel = "noopener";
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  setTimeout(() => URL.revokeObjectURL(objectUrl), 20_000);
}

export function fileNameFor(
  title: string,
  url: string | undefined,
  fallbackExt = "",
  prefix = "skoit",
): string {
  const fromUrl = url
    ? (() => {
        try {
          const path = new URL(url).pathname;
          const last = decodeURIComponent(path.split("/").filter(Boolean).pop() ?? "");
          return /\.[a-z0-9]{2,5}$/i.test(last) ? last : "";
        } catch {
          return "";
        }
      })()
    : "";
  if (fromUrl) {
    return fromUrl;
  }
  const base = slugify(title || "file", "file").slice(0, 80);
  return `${prefix}-${base}${fallbackExt || ""}`;
}

/** Save generated bytes (a built PDF, a rendered QR) without any network. */
export function downloadGenerated(
  filename: string,
  data: Blob | Uint8Array | string,
  mime = "application/octet-stream",
): void {
  const blob =
    data instanceof Blob
      ? data
      : typeof data === "string"
        ? new Blob([data], { type: mime })
        : new Blob([data.slice().buffer as ArrayBuffer], { type: mime });
  saveBlob(blob, filename);
}

/**
 * A download URL that works even when the source refuses cross-origin reads:
 * the console's own server streams the file with a save-attachment header.
 */
export function proxiedDownloadUrl(url: string, filename?: string): string {
  const params = new URLSearchParams({ url });
  if (filename) {
    params.set("filename", filename);
  }
  return `/api/download?${params.toString()}`;
}

/** Download something that lives at a URL, as directly as the browser allows. */
export async function forceDownload(
  url: string,
  title: string,
  options: { ext?: string; prefix?: string; signal?: AbortSignal } = {},
): Promise<{ mode: DownloadMode; filename: string }> {
  const fallbackExt = options.ext ?? extensionFromMime("") ?? "";
  const filename = fileNameFor(title, url, options.ext ?? "", options.prefix ?? "skoit");

  // Only attempt browser-direct for http(s); the proxy handles the rest.
  if (/^https?:\/\//i.test(url)) {
    try {
      const response = await fetch(url, {
        mode: "cors",
        signal: options.signal,
        cache: "no-store",
      });
      if (response.ok) {
        const blob = await response.blob();
        saveBlob(blob, filename);
        return { mode: "blob", filename };
      }
    } catch {
      /* CORS or network — the server route is next */
    }

    // The console's own server streams the file with an attachment header.
    // This succeeds for the many publishers that refuse cross-origin reads,
    // without routing the bytes through a third-party public proxy.
    try {
      const response = await fetch(proxiedDownloadUrl(url, filename), {
        signal: options.signal,
        cache: "no-store",
      });
      if (response.ok) {
        const blob = await response.blob();
        saveBlob(blob, filename);
        return { mode: "relay", filename };
      }
    } catch {
      /* server route refused too — the public relay chain is the last stop */
    }
  }

  const relayed = await relayBytes(url, { signal: options.signal });
  if (isRelayOk(relayed)) {
    const mime = relayed.data.mime || "application/octet-stream";
    const ext = options.ext ?? extensionFromMime(mime) ?? fallbackExt;
    const named =
      ext && !filename.toLowerCase().endsWith(ext) ? `${filename}${ext}` : filename;
    saveBlob(
      new Blob([relayed.data.bytes.slice().buffer as ArrayBuffer], { type: mime }),
      named,
    );
    return { mode: "relay", filename: named };
  }

  try {
    window.open(url, "_blank", "noopener,noreferrer");
    return { mode: "opened", filename };
  } catch {
    return { mode: "failed", filename };
  }
}
